source 'https://rubygems.org'
ruby '2.0.0'

gem 'grape'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'json_spec'
end

group :development, :test do
  gem 'fdoc', :git => 'git@github.com:square/fdoc.git'
  gem 'json-schema', '< 2.0.0' # temporarily avoid change in json-schema require syntax
end
