# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'PokeR'

  app.info_plist['UIMainStoryboardFile'] = 'MainStoryboard'

  app.pods do
    pod 'SVProgressHUD'
  end
end
